// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as TOFU_TOKEN_DECIMALS_ADDR,
    BYTECODE_HASH as TOFU_TOKEN_DECIMALS_HASH
} from "../generated/candidate/TOFUTokenDecimals.sol";

/// @title LibTOFUTokenDecimalsDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `TOFUTokenDecimals`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibTOFUTokenDecimalsDeploy {
    address constant TOFU_TOKEN_DECIMALS_DEPLOYED_ADDRESS = TOFU_TOKEN_DECIMALS_ADDR;
    bytes32 constant TOFU_TOKEN_DECIMALS_DEPLOYED_CODEHASH = TOFU_TOKEN_DECIMALS_HASH;
}
